import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adeyinka Adesope Foundation | AAF",
  description: "Generated by create next app",
};

const roboto = localFont({
  src: [
    {
      path: "../font/Roboto-Italic.ttf",
      style: "italic",
    },
    {
      path: "../font/Roboto-Regular.ttf",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} font-sans`}
        suppressHydrationWarning={true}
      >
        <NavBar />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
